on:
  schedule:
    # Every day at 9:00 UTC/5:00 ET
    - cron:  '0 9 * 1,2,9-12 *'
    # TNF 5:30 AM UTC / 12:30 AM ET
    - cron:  '30 5 * 1,2,9-12 5'
    # Early window: 10:00 PM UTC / 5:00 PM ET
    - cron:  '00 22 * 1,2,9-12 0'
    # Late window: 0:00 UTC / 8:00 ET
    - cron:  '5 0 * 1,2,9-12 1'
    # SNF/MNF: 5:30 UTC / 12:30 ET
    - cron:  '30 5 * 1,2,9-12 1'
    - cron:  '30 5 * 1,2,9-12 2'
  workflow_dispatch:

name: update_current_season_pbp_and_stats

jobs:
  update:
    name: update_pbp
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
           cache-version: 1
           extra-packages: |
            nflverse/nflfastR
            nflverse/nflreadr
            nflverse/nflverse-data
            nflverse/ngsscrapR
            nflverse/fastrmodels
            ropensci/piggyback

      - name: Run pbp update
        run: Rscript -e 'source("R/update_pbp.R")'

      - name: Run player_stats script
        run: Rscript -e 'source("R/update_player_stats.R")'

      - name: Run player_stats_kicking script
        run: Rscript -e 'source("R/update_player_stats_kicking.R")'

      - name: Run participation update
        run: Rscript -e 'source("R/update_pbp_participation.R")'
