on: workflow_dispatch

name: GHA test

jobs:
  gha_test:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.NFLVERSE_GH_TOKEN }}
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}

    steps:
      - uses: actions/checkout@v6
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
           packages: |
            logger

      - name: Run update script
        run: |
          logger::log_layout(logger::layout_gha)
          logger::log_with_separator("Test dhjwelhdjiow2hqdjiow2 hdjio 2hwqjdio 2hewqdij oh2uwi oqdhujw2i oqhduio")
          logger::log_success("This was successful")
          logger::log_error("This is an error")
          logger::log_tictoc("starting a timer")
          Sys.sleep(1)
          logger::log_tictoc("ending a timer")
          logger::log_failure("This should fail now")
        shell: Rscript {0}
